CREATE TABLE IF NOT EXISTS `pix_charges` (
    `idx` INT NOT NULL AUTO_INCREMENT,
    `created_at` DATETIME DEFAULT NULL,
    `created_by` INT DEFAULT NULL,
    `modified_at` DATETIME DEFAULT NULL,
    `modified_by` INT DEFAULT NULL,
    `removed_at` DATETIME DEFAULT NULL,
    `removed_by` INT DEFAULT NULL,
    `active` ENUM('yes', 'no') DEFAULT 'yes',
    `orders_id` INT NOT NULL,
    `payment_gateways_id` INT NOT NULL,
    `gateway_charge_id` VARCHAR(120) DEFAULT NULL,
    `transaction_nsu` VARCHAR(64) DEFAULT NULL,
    `status` ENUM('pendente', 'pago', 'expirado', 'erro') NOT NULL DEFAULT 'pendente',
    `qr_payload` TEXT DEFAULT NULL,
    `qr_image_base64` LONGTEXT DEFAULT NULL,
    `redirect_url` VARCHAR(500) DEFAULT NULL,
    `amount_cents` INT UNSIGNED NOT NULL DEFAULT 0,
    `expires_at` DATETIME NOT NULL,
    `paid_at` DATETIME DEFAULT NULL,
    PRIMARY KEY (`idx`),
    UNIQUE KEY `uq_pix_charge_gateway` (`payment_gateways_id`, `gateway_charge_id`),
    UNIQUE KEY `uq_pix_charge_transaction_nsu` (`transaction_nsu`),
    KEY `idx_pix_charges_order` (`orders_id`, `active`),
    KEY `idx_pix_charges_active_status` (`active`, `status`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
