CREATE TABLE IF NOT EXISTS `orders` (
    `idx` INT NOT NULL AUTO_INCREMENT,
    `created_at` DATETIME DEFAULT NULL,
    `created_by` INT DEFAULT NULL,
    `modified_at` DATETIME DEFAULT NULL,
    `modified_by` INT DEFAULT NULL,
    `removed_at` DATETIME DEFAULT NULL,
    `removed_by` INT DEFAULT NULL,
    `active` ENUM('yes', 'no') DEFAULT 'yes',
    `token` VARCHAR(64) NOT NULL UNIQUE,
    `status` ENUM('aguardando_pagamento', 'pago', 'cancelado', 'expirado') NOT NULL DEFAULT 'aguardando_pagamento',
    `customer_name` VARCHAR(255) NOT NULL,
    `customer_mail` VARCHAR(255) NOT NULL,
    `customer_phone` VARCHAR(20) NOT NULL,
    `ship_zip` VARCHAR(9) NOT NULL,
    `ship_street` VARCHAR(255) NOT NULL,
    `ship_number` VARCHAR(20) NOT NULL,
    `ship_complement` VARCHAR(120) DEFAULT NULL,
    `ship_district` VARCHAR(120) NOT NULL,
    `ship_city` VARCHAR(120) NOT NULL,
    `ship_uf` CHAR(2) NOT NULL,
    `total_cents` INT UNSIGNED NOT NULL DEFAULT 0,
    `paid_at` DATETIME DEFAULT NULL,
    `expires_at` DATETIME NOT NULL,
    PRIMARY KEY (`idx`),
    KEY `idx_orders_status_expires` (`status`, `expires_at`),
    KEY `idx_orders_created` (`created_at`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
